### ISSUE TITLE
Visualizacao do mapa da rede

### ISSUE THREAD

**Issue by hpe95** [fga-gpp-mds/2017.2-SiGI-Op_API#111]
- Vai ter imagem do mapa, e a partir da latitude e longitude dos itens, eles deverao ser mostrados de acordo no mapa.
- Definir quais itens terao que ser possiveis de serem visualizados no mapa.

**Comment by jpmartins201** [comment]
o que vocês bolaram pra começar a fazer?

**Comment by hpe95** [comment]
- [ ] Renderizar o mapa
- [ ] Adicionar marcadores
- [ ] Relacionar os marcadores com as entidades
- [ ] Conexao entre os marcadores

Entidades: Sites (Concentradores, Acessos); Segmentos; Caixa de Emenda; Reserva Tecnica
