### ISSUE TITLE
US04 - Manter Slots do Switches (Back end)

### ISSUE THREAD

**Issue by santana-guilherme** [fga-gpp-mds/2017.2-SiGI-Op_API#54]

**Comment by hpe95** [comment]
Automatizada
Nao tem front
Ao clicar na modal de Switch, vai ter que ser possivel ver a lista dos slots e se eles estao ocupados/livres

**Comment by hpe95** [comment]
Back PTS - 2

**Comment by hpe95** [comment]
Front PTS - 8

Devera mostrar o switch e as portas e seus estados (so verificar se a porta esta como null ou nao)
